### ISSUE TITLE
Validation seems not to work.

### ISSUE THREAD

**Issue by jbellmann** [thymeleaf/thymeleafexamples-petclinic#4]
When I create an new Owner and I fill out the field for 'telephone' with '23412354352' I get the following Internal Server Error:

```
ERROR TemplateEngine - [THYMELEAF][http-bio-8080-exec-4] Exception processing template "owners/createOrUpdateOwnerForm": Exception parsing document: template="null", line 2 - column 48 (owners/createOrUpdateOwnerForm:89)
Apr 10, 2013 9:49:02 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [petclinic] in context with path [/petclinic] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Exception parsing document: template="null", line 2 - column 48 (owners/createOrUpdateOwnerForm:89)] with root cause
org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 48; The content of elements must consist of well-formed character data or markup.
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
    at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1388)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.startOfMarkup(XMLDocumentFragmentScannerImpl.java:2567)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2665)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:607)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:489)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:835)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:764)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:123)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1210)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:568)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:302)
    at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.doParse(AbstractNonValidatingSAXTemplateParser.java:208)
    at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplateUsingPool(AbstractNonValidatingSAXTemplateParser.java:132)
    at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseFragment(AbstractNonValidatingSAXTemplateParser.java:254)
    at org.thymeleaf.spring3.processor.attr.SpringErrorsAttrProcessor.processAttribute(SpringErrorsAttrProcessor.java:107)
    at org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:74)
    at org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
    at org.thymeleaf.dom.Node.applyNextProcessor(Node.java:914)
    at org.thymeleaf.dom.Node.processNode(Node.java:875)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    at org.thymeleaf.dom.Node.processNode(Node.java:894)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    at org.thymeleaf.dom.Node.processNode(Node.java:894)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    at org.thymeleaf.dom.Node.processNode(Node.java:894)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    at org.thymeleaf.dom.Node.processNode(Node.java:894)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    at org.thymeleaf.dom.Node.processNode(Node.java:894)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    at org.thymeleaf.dom.Node.processNode(Node.java:894)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:639)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:621)
    at org.thymeleaf.dom.Node.processNode(Node.java:894)
    at org.thymeleaf.dom.Document.process(Document.java:93)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1243)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1148)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1095)
    at org.thymeleaf.spring3.view.ThymeleafView.renderFragment(ThymeleafView.java:259)
    at org.thymeleaf.spring3.view.ThymeleafView.render(ThymeleafView.java:179)
    at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1208)
    at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:992)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:939)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:936)
    at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:838)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:641)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:812)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:722)
```

When I try with only one digit less '2341235435' everything works better.

**Comment by danielfernandez** [comment]
This is related to https://github.com/thymeleaf/thymeleaf-spring3/issues/14

When you input `2341235435`, validation fails and a validation message should appear. But this message probably includes some markup, which provokes this error.

**Comment by danielfernandez** [comment]
Fixed by https://github.com/thymeleaf/thymeleaf-spring3/commit/d4750387cf5b3ef6227faec08f64ed4ae684957f
